<?php

namespace Marshmallow\Translatable\Cache;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Marshmallow\Translatable\Models\Language;
use Marshmallow\Translatable\Models\Translatable;
use Marshmallow\Translatable\TranslatableConfig;

class TranslatableCache
{
    protected static array $loadedCaches = [];

    protected static ?bool $cacheExists = null;

    public static function get(string $modelClass, int|string $modelId, string $field, int $languageId): ?string
    {
        $cache = static::loadModelCache($modelClass);

        if ($cache === null) {
            return null;
        }

        return $cache[$modelId][$field][$languageId] ?? null;
    }

    public static function has(string $modelClass, int|string $modelId, string $field, int $languageId): bool
    {
        $cache = static::loadModelCache($modelClass);

        if ($cache === null) {
            return false;
        }

        return isset($cache[$modelId][$field][$languageId]);
    }

    public static function buildForModel(string $modelClass): void
    {
        $data = [];

        $translatables = Translatable::query()
            ->where('translatable_type', $modelClass)
            ->get();

        foreach ($translatables as $translatable) {
            $modelId = $translatable->translatable_id;
            $field = $translatable->field;
            $languageId = $translatable->language_id;

            if (! isset($data[$modelId])) {
                $data[$modelId] = [];
            }

            if (! isset($data[$modelId][$field])) {
                $data[$modelId][$field] = [];
            }

            $data[$modelId][$field][$languageId] = $translatable->value;
        }

        static::writeModelCache($modelClass, $data);
    }

    public static function clear(): void
    {
        $cachePath = static::getCachePath();

        if (File::isDirectory($cachePath)) {
            File::deleteDirectory($cachePath);
        }

        static::$loadedCaches = [];
        static::$cacheExists = null;
    }

    public static function clearModel(string $modelClass): void
    {
        $path = static::getModelCachePath($modelClass);

        if (File::exists($path)) {
            File::delete($path);
        }

        unset(static::$loadedCaches[$modelClass]);
    }

    public static function exists(): bool
    {
        if (static::$cacheExists === null) {
            static::$cacheExists = File::isDirectory(static::getCachePath());
        }

        return static::$cacheExists;
    }

    public static function modelCacheExists(string $modelClass): bool
    {
        if (! static::exists()) {
            return false;
        }

        return File::exists(static::getModelCachePath($modelClass));
    }

    protected static function loadModelCache(string $modelClass): ?array
    {
        if (isset(static::$loadedCaches[$modelClass])) {
            return static::$loadedCaches[$modelClass];
        }

        if (! static::modelCacheExists($modelClass)) {
            return null;
        }

        $cache = require static::getModelCachePath($modelClass);
        static::$loadedCaches[$modelClass] = $cache;

        return $cache;
    }

    protected static function writeModelCache(string $modelClass, array $data): void
    {
        $cachePath = static::getCachePath();

        if (! File::isDirectory($cachePath)) {
            File::makeDirectory($cachePath, 0755, true);
        }

        $content = '<?php' . PHP_EOL . PHP_EOL;
        $content .= '// Generated by translatable:cache' . PHP_EOL;
        $content .= '// Model: ' . $modelClass . PHP_EOL;
        $content .= '// Generated at: ' . now()->toDateTimeString() . PHP_EOL . PHP_EOL;
        $content .= 'return ' . var_export($data, true) . ';' . PHP_EOL;

        File::put(static::getModelCachePath($modelClass), $content);

        static::$loadedCaches[$modelClass] = $data;
        static::$cacheExists = true;
    }

    public static function getCachePath(): string
    {
        return TranslatableConfig::getCachePath() . '/translatables';
    }

    public static function getModelCachePath(string $modelClass): string
    {
        $filename = Str::replace('\\', '_', $modelClass) . '.php';

        return static::getCachePath() . '/' . $filename;
    }

    public static function flush(): void
    {
        static::$loadedCaches = [];
        static::$cacheExists = null;
    }
}
