<?php

namespace Marshmallow\Translatable\Cache;

use Illuminate\Support\Facades\File;
use Marshmallow\Translatable\Models\Language;
use Marshmallow\Translatable\Models\Translation;
use Marshmallow\Translatable\TranslatableConfig;

class TranslationCache
{
    protected static ?array $cache = null;

    protected static ?bool $cacheExists = null;

    public static function get(string $locale, string $group): ?array
    {
        $cache = static::loadCache();

        if ($cache === null) {
            return null;
        }

        return $cache[$locale][$group] ?? null;
    }

    public static function has(string $locale, string $group): bool
    {
        $cache = static::loadCache();

        if ($cache === null) {
            return false;
        }

        return isset($cache[$locale][$group]);
    }

    public static function build(): void
    {
        $cache = [];

        $languages = Language::active()->get();

        foreach ($languages as $language) {
            $cache[$language->code] = [];

            $translations = Translation::query()
                ->where('language_id', $language->id)
                ->whereNotNull('value')
                ->where('value', '!=', '')
                ->get();

            foreach ($translations as $translation) {
                $group = $translation->group;

                if (! isset($cache[$language->code][$group])) {
                    $cache[$language->code][$group] = [];
                }

                $key = $translation->context
                    ? "{$translation->key}.{$translation->context}"
                    : $translation->key;

                $cache[$language->code][$group][$key] = $translation->value;
            }
        }

        static::write($cache);
    }

    public static function clear(): void
    {
        $path = static::getCachePath();

        if (File::exists($path)) {
            File::delete($path);
        }

        static::$cache = null;
        static::$cacheExists = null;
    }

    public static function exists(): bool
    {
        if (static::$cacheExists === null) {
            static::$cacheExists = File::exists(static::getCachePath());
        }

        return static::$cacheExists;
    }

    protected static function loadCache(): ?array
    {
        if (static::$cache !== null) {
            return static::$cache;
        }

        if (! static::exists()) {
            return null;
        }

        static::$cache = require static::getCachePath();

        return static::$cache;
    }

    protected static function write(array $cache): void
    {
        $path = static::getCachePath();
        $directory = dirname($path);

        if (! File::isDirectory($directory)) {
            File::makeDirectory($directory, 0755, true);
        }

        $content = '<?php' . PHP_EOL . PHP_EOL;
        $content .= '// Generated by translatable:cache' . PHP_EOL;
        $content .= '// Generated at: ' . now()->toDateTimeString() . PHP_EOL . PHP_EOL;
        $content .= 'return ' . var_export($cache, true) . ';' . PHP_EOL;

        File::put($path, $content);

        static::$cache = $cache;
        static::$cacheExists = true;
    }

    public static function getCachePath(): string
    {
        return TranslatableConfig::getCachePath() . '/translations.php';
    }

    public static function flush(): void
    {
        static::$cache = null;
        static::$cacheExists = null;
    }
}
