<?php

namespace Marshmallow\Translatable\Cache;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\File;

class TranslatableCache
{
    protected static array $loadedCaches = [];

    protected static ?bool $cacheExists = null;

    public static function getCachePath(): string
    {
        return base_path('bootstrap/cache/translatables');
    }

    public static function getModelCachePath(string $modelClass): string
    {
        $filename = Str::replace('\\', '_', $modelClass) . '.php';

        return static::getCachePath() . '/' . $filename;
    }

    public static function cacheExists(): bool
    {
        if (static::$cacheExists === null) {
            static::$cacheExists = File::isDirectory(static::getCachePath());
        }

        return static::$cacheExists;
    }

    public static function modelCacheExists(string $modelClass): bool
    {
        if (! static::cacheExists()) {
            return false;
        }

        return File::exists(static::getModelCachePath($modelClass));
    }

    public static function loadModelCache(string $modelClass): ?array
    {
        if (isset(static::$loadedCaches[$modelClass])) {
            return static::$loadedCaches[$modelClass];
        }

        if (! static::modelCacheExists($modelClass)) {
            return null;
        }

        $cache = require static::getModelCachePath($modelClass);
        static::$loadedCaches[$modelClass] = $cache;

        return $cache;
    }

    public static function get(string $modelClass, int|string $modelId, string $field, int $languageId): ?string
    {
        $cache = static::loadModelCache($modelClass);

        if ($cache === null) {
            return null;
        }

        return $cache[$modelId][$field][$languageId] ?? null;
    }

    public static function has(string $modelClass, int|string $modelId, string $field, int $languageId): bool
    {
        $cache = static::loadModelCache($modelClass);

        if ($cache === null) {
            return false;
        }

        return isset($cache[$modelId][$field][$languageId]);
    }

    public static function clear(): void
    {
        $cachePath = static::getCachePath();

        if (File::isDirectory($cachePath)) {
            File::deleteDirectory($cachePath);
        }

        static::$loadedCaches = [];
        static::$cacheExists = null;
    }

    public static function clearModel(string $modelClass): void
    {
        $path = static::getModelCachePath($modelClass);

        if (File::exists($path)) {
            File::delete($path);
        }

        unset(static::$loadedCaches[$modelClass]);
    }

    public static function writeModelCache(string $modelClass, array $data): void
    {
        $cachePath = static::getCachePath();

        if (! File::isDirectory($cachePath)) {
            File::makeDirectory($cachePath, 0755, true);
        }

        $content = '<?php' . PHP_EOL . PHP_EOL;
        $content .= '// Generated by translatable:cache' . PHP_EOL;
        $content .= '// Model: ' . $modelClass . PHP_EOL;
        $content .= '// Generated at: ' . now()->toDateTimeString() . PHP_EOL . PHP_EOL;
        $content .= 'return ' . var_export($data, true) . ';' . PHP_EOL;

        File::put(static::getModelCachePath($modelClass), $content);

        static::$cacheExists = true;
    }

    public static function flush(): void
    {
        static::$loadedCaches = [];
        static::$cacheExists = null;
    }
}
