<?php

namespace Marshmallow\Translatable\Cache;

use Illuminate\Support\Facades\File;

class TranslationCache
{
    protected static ?array $cache = null;

    protected static ?bool $cacheExists = null;

    public static function getCachePath(): string
    {
        return base_path('bootstrap/cache/translations.php');
    }

    public static function cacheExists(): bool
    {
        if (static::$cacheExists === null) {
            static::$cacheExists = File::exists(static::getCachePath());
        }

        return static::$cacheExists;
    }

    public static function loadCache(): ?array
    {
        if (static::$cache !== null) {
            return static::$cache;
        }

        if (! static::cacheExists()) {
            return null;
        }

        static::$cache = require static::getCachePath();

        return static::$cache;
    }

    public static function getGroupTranslationsFor(string $language): ?array
    {
        $cache = static::loadCache();

        if ($cache === null) {
            return null;
        }

        return $cache[$language]['group'] ?? null;
    }

    public static function getSingleTranslationsFor(string $language): ?array
    {
        $cache = static::loadCache();

        if ($cache === null) {
            return null;
        }

        return $cache[$language]['single'] ?? null;
    }

    public static function get(string $language, string $group, string $key): ?string
    {
        $cache = static::loadCache();

        if ($cache === null) {
            return null;
        }

        return $cache[$language][$group][$key] ?? null;
    }

    public static function has(string $language, string $group, string $key): bool
    {
        $cache = static::loadCache();

        if ($cache === null) {
            return false;
        }

        return isset($cache[$language][$group][$key]);
    }

    public static function clear(): void
    {
        if (File::exists(static::getCachePath())) {
            File::delete(static::getCachePath());
        }

        static::$cache = null;
        static::$cacheExists = null;
    }

    public static function writeCache(array $data): void
    {
        $content = '<?php' . PHP_EOL . PHP_EOL;
        $content .= '// Generated by translation:cache' . PHP_EOL;
        $content .= '// Generated at: ' . now()->toDateTimeString() . PHP_EOL . PHP_EOL;
        $content .= 'return ' . var_export($data, true) . ';' . PHP_EOL;

        File::put(static::getCachePath(), $content);

        static::$cacheExists = true;
        static::$cache = $data;
    }

    public static function flush(): void
    {
        static::$cache = null;
        static::$cacheExists = null;
    }
}
